### ISSUE TITLE
18 Identify County for requested image groups

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1613]
When a transcriber submits a request for an image group, their SC gets an email that only states the image group name, for example: "....requests to obtain images in Newport-Catholic OT/NewportCatholi". There is no indication of which county, Newport is in, so the SC does not know where to request the group from.

**Comment by edickens** [comment]
They need the Source name.  That will give County, Place, Church and Register Type.

**Comment by SteveBiggs** [comment]
Will it? The Source name is "Image Server".

**Comment by edickens** [comment]
I meant that we should quote the path to the Source.

**Comment by edickens** [comment]
Should the email also be sent to the CC, and not as a bcc, so that the SC knows who to contact.

**Comment by Captainkirkdawson** [comment]
I have deployed a changed email that has a link to the image server group to all of the information is available to the SC
It has been deployed to test3. Unfortunately I have NOT been able to test as I have to access myself. Perhaps @SteveBiggs can test

I have not done a cc to CC as I think that inappropriate. It may be that the SC will not want to pursue the request.

**Comment by SteveBiggs** [comment]
I clicked on 'Email CC' for an image group and it returned with the red "We're sorry ....." error page.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs my mistake a typo; please retry

**Comment by SteveBiggs** [comment]
The 'Email SC' link now works and I received the email with the clickable link to the group, however, when I logged in as the SC and clicked it, I got the message "can not locate image group". Is this because the group has not yet been allocated to my syndicate so I cannot access it? So the SC still does not know what group from which county has been requested (although I can see it in the groups available under Assignments).

Rather than a link to the group, can the full details of the group including county be put in the email?

**Comment by Captainkirkdawson** [comment]
Have changed to do full look up and deployed to test3. @SteveBiggs does this meet the need?

**Comment by SteveBiggs** [comment]
I'm afraid that clicking the 'Email SC' link gives the red "We're sorry ...." message again now.

**Comment by Captainkirkdawson** [comment]
Sorry @SteveBiggs my spelling these days is terrible. Can you retry please (This is an issue of not being able to test the code myself)

**Comment by SteveBiggs** [comment]
Perfect! Thanks
