### ISSUE TITLE
There appear to be a significant number of orphan search records on FreeREG

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2423]
There are 51,992,244 csv entries and 52,612,974 search records ie 620,730 records.

**Comment by edickens** [comment]
Probably deletions.  Entries uploaded as shown by county fairly closely matches the Footer total.

**Comment by Captainkirkdawson** [comment]
After cleaning out files that were disconnected from a register we are left with 613,619 orphan records.
The use of the chain look up for the location now enables them to be identified when they are "used" as the location field will now show 'Unknown location'. An example follows
![unknown location.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/957ebf22-ae6d-4672-af64-27b7325511d5)
There are other examples for the same file.
What is clear is that the replacement of a file did not delete the search records of the earlier file since the two records are for the same entry EXCEPT that the entry for the first search record no longer exists. Why is unclear.
The following is the entry that exists
![exists.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/ffc88af4-3da3-42c1-baa0-7652ec9eed5f) 
Note it is record 170 in a Parish Register and it was created on 19 Jan 2019
We cannot review the missing entry since it does not exist. But we can get some clues from the search record.
![does not exist.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/bb7e725b-c65b-4ae2-a145-ee27b22add20)
This shows that that it is an unspecified register and that it was record number 12,250. It was created  on 1 Nov 2016
My hypothesis is that the coordinator split the original extremely large file into manageable parts and corrected the register to Parish Register. The original file was then deleted but the deletion timed out because of the large number of entries and search records to be deleted.
I suspect there are many cases of this type.
Looking at 1 day on 1 server shows that it delivered 7,471 unknown location records out of 357,750 records or 2%.

**Comment by edickens** [comment]
This has been assigned to me but I am not sure what I am supposed to do.
Are these actually "Searches" or the server doing an index search to find an entry?
These are STS records when a lot of large files were split.  But this is stopped now and I have told CCs that it is not necessary.  Just don't create large files in the future.
But I did see that there must have been some entry deletions on Wednesday, although this could have been Kirk doing some tidying up.

**Comment by Captainkirkdawson** [comment]
Sorry I had written a post with 5t I wanted feed back upon; appears that I did not save it

**Comment by Captainkirkdawson** [comment]
Given the preceding analysis there are a number of possible ways of addressing the issue.

1. Do nothing. It has clearly been there for several year. However it is now clearly visible to the researcher that there are data problems in our database.
2. Do not display records with the Unknown location. Leaves the problem data in the database but no one but us knows that the number of actual records is wrong and inflated.
3. Delete the entry when it is retrieved. Similar to 2 but slowly cleans up the database. Records are not deleted until someone finds them. Will slow the display of the search results by a small amount for each such record. 
4. Accumulate the record not being displayed and put them in a rake task that is spun off to run independently Avoids slowing down the display of results but a little more complex to program.
5. Write a rake task to analyse the log and locate the problem records and run as a scheduled task over night. Somewhat complex coding, that achieves the same results as 3-5 but is independent of the operational code.
6. Extend the rake code in 5 to detect the original problem file and destroy all search  records created from that file. Cleans up the database slowly but surely over the years but much faster than option 5.
7. Write a slow running rake task that ensures the entry for all 50 million search records exists and if not remove it. Likely would take several weeks to run and would need interesting code to be able to restart the task from where it had finished. Cleans the database in a finite time.

**Comment by edickens** [comment]
Hi Kirk,

I'm not sure that I am the only one to take a decision on this because I am not sure that I completely understand the problem.

You talk of "Search records", but I assume that these are Data entries. And if I am correct, these have been left there when a batch was being deleted, so the data entry is in the database somewhere else.  By deleting them we are not losing information.  These are data entries which are not needed but have been counted in the overall database count.  Deleting them will reduce the count by 600K+ entries.

If I am correct, I recommend that you do option 3.  It sounds the easiest to program, but it also means that the reduction in database entry count will probably not be noticed as ir is reduced gradually.

I do recommend that you put something fairly comprehensive in the program notes to say why the code is there, because sometime in the future someone may wonder what is going on, delete the code and then the problem will recur if all the orphans have not been removed.  I'm sure that at some time there will be a full tidy up when a new database management system is introduced, but hopefully not in our lifetime.

Many thanks,
Eric

**Comment by Sherlock21** [comment]
Writing as one who no doubt has contributed to creating these part records ( during deleting large files for CC's ) and also as one who has come across the results quite regularly when trying to resolve CC's various requests, I have asked several times for these to be cleaned up ( ie removed)
I would therefore repeat what I have said before: if we have a database and wish it to be taken seriously by researches, then it must be accurate. If researchers regularly get search results that have these part records, we will loose our credibility. 

SO I vote for the option 7 as my first choice,
followed by option 6 as second choice, whichever would be the quickest to get the complete job done.


Doing nothing ( option 1) is not a credible option.

**Comment by edickens** [comment]
Eric B,

If I understand Kirk's options correctly, if he does Option 3 the entry will be trapped before it is shown to the researcher so it would then appear that all is working correctly, even if it will take some time to clean the database.

Eric D

**Comment by Captainkirkdawson** [comment]
@edickens So you understand better. A file has many entries. But we do not search against the entries directly. We create a search record for each entry and search are conducted against the search record. Every entry has a search record. What has happened is that the entries in some 600,000 cases have been deleted but not their search record.

**Comment by edickens** [comment]
TY.  So deleting these Search records will not change the overall number of transcribed entries and should not therefore change the count of the number of entries transcribed into the database.

Deleting them should also not affect the results of a search as these records are in effect duplicates or unwanted.

**Comment by Captainkirkdawson** [comment]
Correct

**Comment by edickens** [comment]
So Kirk.  I suggest option 3 and Eric B option 7.  I can understand Eric's view that it should be cleaned up fully now, but I can see the amount of programming and processing needed.  Which will you do?

**Comment by Captainkirkdawson** [comment]
Given the implications of the various options I will need a full decision by the scrum before undertaking any action. Have yet to have any feedback from Steve and Pat

**Comment by SteveBiggs** [comment]
I agree with EricD - option 3. We have enough to get done without creating another large coding task and it stops the orphan records from being visible to the researcher while gradually cleaning up.

**Comment by PatReynolds** [comment]
Thanks for offline comment from Kirk that doing 3 does not preclude the later development of 7, so I conclude that 3 should be undertaken to resolve this issue, and option 7 created as a version2 story.

**Comment by Captainkirkdawson** [comment]
This story now limited to option 3. Option 7 to be in new story

**Comment by SteveBiggs** [comment]
I agree with EricD - option 3. We have enough to get done without creating
another large coding task and it stops the orphan records from being
visible to the researcher while gradually cleaning up.

Steve

Stephen Biggs
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Code has been added to detect, log and delete any search record that is an orphan for any reason.
Deployed to test3.
Search before deployment
![before.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/c4071d11-df46-4699-b821-1dc87de5ff3b)
Log before
![beforea.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/f74b06e2-a022-4b4a-a396-72ce30bac728)
Results after 
![after.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/68e144cb-8ee7-49a4-8805-6dc76a7cf8e3)
@SteveBiggs @edickens @Sherlock21 search needs checking to see if problems have been introduced.

**Comment by SteveBiggs** [comment]
Made several searches on test3 including one which had 2 orphan records that were removed on a repeat search. All looks good.

**Comment by edickens** [comment]
Sorry to be so long getting around to this.
My usual search has brought up two Unknown locations amongst the 139 results in Test3...

![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/a4cf17e1-d2c1-4f1e-9f83-20253ef73685)

![Capture1.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/7916fdab-13af-4afe-8cc4-65d7fe0003c3)

**Comment by Captainkirkdawson** [comment]
@edickens You must run the search twice to see the impact. The first search will have deleted them

**Comment by edickens** [comment]
Now it doesn't find these two people.  E

**Comment by edickens** [comment]
I've done a bit of research on the first one that is missing.  In FamilySearch...

![Capture2.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/f562bb30-978e-49f4-bcfa-5696efacc88f)

This then lead me to SOMHIGBA.  The year 1881 does not seem to be there in Test3.  The file has a lot of blank entries and one that is a typing error.  So that could be why the search does not now find this person.

In Production there are two batches and the typing error has been corrected.  The entry #97 in SOMHIGBA1 is there.

If I do the search in FR Production, the search works and finds the Place.

![Capture3.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/7c1ae7eb-49f4-4301-a07a-f4b7020482a5)

So all would seem to be well.

**Comment by Sherlock21** [comment]
Eric D's suggestion set me thinking that Test3 data has been left behind somehow, and we should use Production to test this one out.
So that's what I did, using my previous person: SANDERCOCK of West Woolfardisworthy , for Devon Baptisms and using Nearby.
Sadly, the result still contains the same one record that has no county.
SO all is not well in my view.


<img width="945" alt="Screenshot 2021-06-22 at 13 36 23" src="https://user-images.githubusercontent.com/9368704/122925676-fb36ef00-d35e-11eb-9271-3c73b0a7b35b.png">

**Comment by Captainkirkdawson** [comment]
@Sherlock21 Yes test3 data is old and has many warts
Please run that search a second time on production and the record should no longer appear

**Comment by Sherlock21** [comment]
In Production, If I repeated the same test for Sandercock, but instead of using Nearby, I just went for Cornwall / Lewannick, I get exactly the same 2 records as before - ie one record WITH the County displayed and one record without the County.

and attempting to view the record with no county shown, just brings up an Error screen ( as before)
- so this is not an issue caused by using "Nearby"

**Comment by Sherlock21** [comment]
I have repeated the search in Production, just now and still get the mystery record if I use Nearby.
Search is: Devon / West Woolfardisworthy/ Sandercock/ Baptism/ 1800 to 1830 with Nearby selected.
the odd record n the results is Betsey Ann SANDERCOCK with place shown as Lewannick, but no County.
yet if I follow the "View" on this result, the correct County of Cornwall is shown on the record.
( also another spelling Betsy Ann SANDERCOCK in Cornwall / Lewannick is shown in full )

IF I run the same spec query but for County = Cornwall and no place name, I dont get the record for Betsey that is above.

**Comment by PatReynolds** [comment]
Corrections will continue to be made as and when they are found.

**Comment by stsccfr** [comment]
I suppose this can be closed now. As of this date, we have 64,583,001 freereg1_csv_entries and 64,560,628 search_records.  Whatever code was added to slowly reduce these seems to be working, as Kirk's original observation was 613,619 orphans (except that I don't think these are orphans but rather parents with no children, as the search_records are created from the freereg1_csv_entries.)
