### ISSUE TITLE
Resetting a password

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#657]
Some have problems resetting a password.  The SC needs advice.

**Comment by edickens** [comment]
I am finding that transcribers are not being able to access FR.  They try to log in but just get bounced back to the Homepage.  When this happens they email me, or their SC who emails me, as they do not know what to do.
Bouncing back to the Homepage can be because their Password is wrong or they are Active = No.  The SC should check their profile. They can find it by UserID, Name or Email address.  First check that their email address is correct in their profile.  Then check if they are Active.  If both of these are OK, then it will be the Password.  If the transcriber says that they have sent requests to reset their password, but they don't get the email to reset it, then this can be their ISP rejecting our reg-web emails.  We should fix this soon.  But an easier way is for the SC to send "Send password change request".  This seems to get through.  That should get them going again.
If they are entering the wrong UserID, this is reported.  However, rather than contacting their SC, they should first try logging on with their email address.  If this gets them in then they will find their UserID.  E

**Comment by Captainkirkdawson** [comment]
This is just not true! It was true but it was fixed in story 505 about a
week ago.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
But I have had someone today saying that they "have been frozen out of 
FR", another who said that FR "would not accept their password", and Pat 
has not been able to get in and reset her password.  That is three 
people just today.  But people never really give me a description of 
what happened.  Just say "they couldn't".  So something is still not 
working properly which is why I tried to do a write-up of what a CC 
should do if someone says that they cannot log in.  Please amend as 
necessary.  E

**Comment by Captainkirkdawson** [comment]
SC should check their profile. They can find it by UserID, Name or Email address. First check that their email address is correct in their profile. Then check if they are Active. If both of these are OK, then it will be the Password. If the transcriber says that they have sent requests to reset their password, but they don't get the email to reset it, then this can be their ISP rejecting our reg-web emails. We should fix this soon. But an easier way is for the SC to send "Send password change request". This seems to get through. That should get them going again.
If they are entering the wrong UserID, this is reported. However, rather than contacting their SC, they should first try logging on with their email address. If this gets them in then they will find their UserID. E

**Comment by AlOneill** [comment]
Now documented on Info for Coords and Info for Transcribers.
